// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop()).last();
      if (this.scores()[0] > 21) {
        return this.trigger('endGame', this);
      }
    };

    Hand.prototype.stand = function() {
      return this.trigger('dealerTurn', this);
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.adjustedScore = function() {
      var scores;
      scores = this.scores();
      if (scores.length === 1) {
        return scores[0];
      } else if (scores[1] > 21) {
        return scores[0];
      } else {
        return Math.max(scores[0], scores[1]);
      }
    };

    Hand.prototype.dealerPlay = function() {
      var score;
      if (!this.at(0).get('revealed')) {
        this.at(0).flip();
      }
      score = this.scores();
      if (score.length === 2 && score[1] <= 21) {
        score = score[1];
      } else {
        score = score[0];
      }
      if (score < 17) {
        this.hit();
        return this.dealerPlay();
      } else {
        return this.trigger('endGame', this);
      }
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
